version: "3.9"
services:
  query-service:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - dynamodb
    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_DEFAULT_REGION=us-east-1
    networks:
      - appnet

  dynamodb:
    image: amazon/dynamodb-local
    ports:
      - "8001:8000"
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
