name: Test & Deploy for Processing Service

on:
  push:
    branches: [ "file-processing-service" ]

jobs:
  refresh:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2

      - name: Start ASG instance refresh
        run: |
          aws autoscaling start-instance-refresh \
            --auto-scaling-group-name procsrcv-asg \
            --preferences MinHealthyPercentage=90

